# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-16 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=250)),
                ('desc', models.TextField(max_length=400)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=250)),
                ('desc', models.TextField(max_length=400)),
                ('unit_price', models.PositiveIntegerField(default=0)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit_measure', models.CharField(max_length=250)),
                ('reorder_level', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('profile_photo', models.ImageField(upload_to='images/')),
                ('bio', models.TextField()),
            ],
        ),
    ]
